[package]
name = "tipchune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rsa = "0.6.1"
sha2 = "0.10.2"
thiserror = "1.0.31"
